Setup optional redirect after requires_confirmation error & doc
Flask-Middleware/flask-security pull request #393
Opened 2020-09-27 11:14 UTC by SnaKyEyeS

Added an option "SECURITY_REQUIRES_CONFIRMATION_ERROR_VIEW". If set to an URL endpoint, will redirect a user who tries to login with an unconfirmed email address while flashing the default error message & passing the email as an argument.

I was unable to check if the sphinx doc could build properly, I had an ``invalid command 'sphinx_build'`` error when trying to do so (?). However, as I didn't add much, it should be no problem.

I didn't add any specific test for this option (not too sure how I'd have to to that to be fair), but if you deem it important, I can look into it !

2020-09-27 16:42 UTC, jwag956 requested changes
Yes - tests are required! You should write a single test in test_confirmable - that when you set your new option you in fact get redirected upon login.

/reset (forgot password) also has same response - the new redirect code should probably be there as well? Unified signin as well (look for requires_confirmation method call).

2020-09-27 16:44 UTC, jwag956 requested changes

2020-09-27 16:44 UTC, jwag956 commented on docs/configuration.rst
> +    Default behavior is to reload the login form with an error message without redirecting to an other page.
if you add support in the other 2 places - be sure to update this comment.

2020-09-27 16:44 UTC, jwag956 commented on flask_security/views.py
> +        if form.requires_confirmation and _security.requires_confirmation_error_view:
please follow convention in file and use config_value("REQUIRES_CONFIRMATION_ERROR_VIEW")

2020-09-27 16:49 UTC, SnaKyEyeS commented on docs/configuration.rst
> +    Default behavior is to reload the login form with an error message without redirecting to an other page.
Which other 2 places...?

2020-09-27 16:50 UTC, SnaKyEyeS commented on flask_security/views.py
> +        if form.requires_confirmation and _security.requires_confirmation_error_view:
Sure ! Just a question: why use _security.var_name when using redirect(get_url(...)) and config_value("VAR_NAME") in other places...?

2020-09-27 16:54 UTC, jwag956 commented on flask_security/views.py
> +        if form.requires_confirmation and _security.requires_confirmation_error_view:
Hmm - good point - so much for conventions - you actually properly followed file conventions - so leave it as you had it!

2020-09-27 20:55 UTC, jwag956 commented on docs/configuration.rst
> +    Default behavior is to reload the login form with an error message without redirecting to an other page.
Thanks for the fixes - in my overall comments I pointed out that there are 3 places where we return 'confirmation needed' as an error: /login, /reset, /us-login

It would seem to be consistent that all three have this same optional redirect applied. Search for 'required_confirmation' in the code.

2020-09-27 21:22 UTC, SnaKyEyeS commented on docs/configuration.rst
> +    Default behavior is to reload the login form with an error message without redirecting to an other page.
Ah yes I’look into it ! :)

2020-09-27 23:39 UTC, SnaKyEyeS commented on docs/configuration.rst
> +    Default behavior is to reload the login form with an error message without redirecting to an other page.
I added support for /reset and /us-signin aswell, though I am less confident on what I did for the us-signin since I have never used it before in my application - just to be safe, better double-check what I did there.

2020-09-28 14:39 UTC, jwag956 approved these changes

2020-09-28 14:39 UTC, merged