Add a 2FA Validity Window/Blacken Files
Flask-Middleware/flask-security pull request #401
Opened 2020-10-12 21:22 UTC by baurt

It is sometimes preferable to have two factor authentication with a grace period where one does not have to revalidate the second factor.  This pull request adds such a functionality by setting a cookie with a signed token confirming that the user has been authenticated within a given time frame and does not need to go through the process again. This is an OWASP recommendation for improving the overall UX (see https://cheatsheetseries.owasp.org/cheatsheets/Multifactor_Authentication_Cheat_Sheet.html)

Added 3 configuration options `SECURITY_TWO_FACTOR_ALWAYS_VALIDATE`, `SECURITY_TWO_FACTOR_VALIDITY_SALT` and `SECURITY_TWO_FACTOR_LOGIN_VALIDITY`.  In the event of a compromise, the cookies can be invalidated by resetting a user's `fs_uniquifier`. 

Also, tests were failing due to Black reformatting them so all files were ran through Black as well.

2020-10-12 22:05 UTC, jwag956 commented
I will look at the content closely - but many of the changes were due to formatting - that shouldn't be since it always passes 'black' - so somehow there must be some configuration difference.

Could you try to figure out why? otherwise when I get it - it will reformat again...

That will reduce the PR by a bunch.....

2020-10-12 22:16 UTC, baurt commented
I'm currently changing a couple of things.  I didn't realize some of the tests could potentially fail if two functions were called within the same second.

I don't know what the issue is. I am currently using version `20.8b1`, so I don't know if they changed something between versions or not.  I'll look at see if I can find what the issue is. It's odd that it's changed, since I run `pre-commit run --all-files`.

2020-10-12 22:20 UTC, jwag956 commented
Odd - I just use pre-commit and it picks up 'stable' which is 20.8b1... The most strange thing is that is is removing a space after """?

2020-10-13 02:26 UTC, baurt commented
I think it has something to do with the way that black is formatting docstrings, via https://github.com/psf/black/pull/1053.

There are several issues complaining about the way it handles docstrings since the first 20 version.

Even now, I see that it failed the black check, even though they pass locally and in the Travis ci that's built in my fork.

2020-10-13 15:21 UTC, jwag956 commented
Odd - but why are we getting different versions? There hasn't been a black release since august - and you can see in the travis logs that I have built master etc many times since then...
One thing I noticed - but it appears that using pre-commit -we can't see which version and from where it is picking up black  - it isn't actually pip installed from what I can tell.

2020-10-13 15:35 UTC, baurt commented
What I don't really understand is that it's not even returning the same number of modified files.  The most recent build only would have changed 8 files, but I initially changed around 25.

I wonder if it's using some sort of cached version?  I know that pre-commit builds an environment for each hook and runs the hook from that environment.  
The thing that is driving me crazy is that this is the results from `pre-commit run --all-files`.  This is the same commit that most recently failed on travis.
![Image](https://user-images.githubusercontent.com/49296311/95882746-ac50a880-0d3f-11eb-950c-64107c721f87.png)

2020-10-13 15:37 UTC, jwag956 commented
It is definitely caching things - black has a cache and so does pre-commit.
I will post a PR that attempts to fix this (by running pre-commit autoupdate prior to running pre-commit).

2020-10-13 15:48 UTC, baurt commented
I'll keep an eye out for that and then rebase this pr on the new version.

2020-10-13 17:50 UTC, jwag956 commented
I am going to be traveling for the next week - so review comments will likely be delayed..

Thanks for doing this.

2020-10-13 18:18 UTC, baurt commented
No worries. Should be easier to view now, since I rebased and squashed some commits. 

Safe travels!

2020-10-15 20:21 UTC, jwag956 requested changes
unified_signin also calls tf_login - so it needs the same new logic...

- I made a few comments about the remember token/cookie w.r.t. JSON. Should we support non-form/JSON front ends to be able to save the token (i.e. return the token on successfull login) and they can return it on next login attempt? or say that this feature relies on cookies?
Not sure myself which way to go.

I haven't looked carefully at the default cookie options - but this one should be http-only, probably secure, and maybe same-site?

2020-10-15 20:21 UTC, jwag956 commented on docs/api.rst
> +.. data:: tf_validation_token_set
curious - what's your use case for having a signal for this - we don't send a signal for the remember cookie or session cookie.

2020-10-15 20:21 UTC, jwag956 commented on docs/two_factor_configurations.rst
> +    app.config['SECURITY_TWO_FACTOR_VALIDITY_SALT']='230129812443702341504339573704856364139'
I don't think there is any reason to change the 'salt' - these token salts are really keys  - not cryptographic salts.

2020-10-15 20:21 UTC, jwag956 commented on flask_security/twofactor.py
> +def generate_tf_validity_token(tf_user_id):
I assume this is fs_uniqifier - lets change the param name and docstring

2020-10-15 20:21 UTC, jwag956 commented on flask_security/twofactor.py
> +    :param form_user_uniquifier: The ``fs_uniquifier`` of the submitting user.
nit: lets not call it 'form_user' - this method could be called via json API or whatever.

2020-10-15 20:21 UTC, jwag956 commented on flask_security/twofactor.py
> +        max_age = int(get_within_delta("TWO_FACTOR_LOGIN_VALIDITY").total_seconds())
wouldn't it be better to have the token be timed (like many of them are) independent of the cookie - again - that would allow all this to be used with a JSON API (which we should support).

2020-10-15 20:21 UTC, jwag956 commented on tests/test_two_factor.py
> +
could we add a test that user.tf_reset will cause the cookie to no longer work?

2020-10-15 20:42 UTC, baurt commented on docs/api.rst
> +.. data:: tf_validation_token_set
I have a signal purely to test that the contains the correct token.  I was running into some tests that would fail because the cookie was set and the verifying token were generated at different times.  Therefore, they tokens would be different.  This way, I can be sure that the cookie's contents are valid.

2020-10-15 20:45 UTC, baurt commented on docs/two_factor_configurations.rst
> +    app.config['SECURITY_TWO_FACTOR_VALIDITY_SALT']='230129812443702341504339573704856364139'
Good point. I was mimicking the 'SECURITY_PASSWORD_SALT' above, but it's probably unnecessary here.

2020-10-15 20:46 UTC, jwag956 commented on docs/two_factor_configurations.rst
> +    app.config['SECURITY_TWO_FACTOR_VALIDITY_SALT']='230129812443702341504339573704856364139'
yea - that's a completely different kind of 'salt'

2020-10-15 20:53 UTC, baurt commented on flask_security/twofactor.py
> +        max_age = int(get_within_delta("TWO_FACTOR_LOGIN_VALIDITY").total_seconds())
both the cookie and the token are actually timed. I figured it would be better if they were both timed.

2020-10-15 21:02 UTC, baurt commented on tests/test_two_factor.py
> +
looking at `tf_reset`, it appears that it doesn't change the `fs_uniquifier`. If we want `tf_reset` to invalidate the token, it should then also change the uniquifier

2020-10-15 21:22 UTC, baurt commented on flask_security/twofactor.py
> +def generate_tf_validity_token(tf_user_id):
Good point.  Changing.

2020-10-15 21:23 UTC, baurt commented on flask_security/twofactor.py
> +    :param form_user_uniquifier: The ``fs_uniquifier`` of the submitting user.
Changed.

2020-10-15 21:25 UTC, jwag956 commented on tests/test_two_factor.py
> +
good point - although reset_user_access() does - maybe that is enough? lets test that though..

2020-10-15 21:25 UTC, jwag956 commented on flask_security/twofactor.py
> +        max_age = int(get_within_delta("TWO_FACTOR_LOGIN_VALIDITY").total_seconds())
sounds reasonable.

2020-10-15 21:26 UTC, jwag956 commented on docs/api.rst
> +.. data:: tf_validation_token_set
ok - if it just for testing there are other ways - is this useful for clients?

2020-10-15 21:28 UTC, baurt commented on docs/two_factor_configurations.rst
> +    app.config['SECURITY_TWO_FACTOR_VALIDITY_SALT']='230129812443702341504339573704856364139'
Easy enough to change.  Done.

2020-10-15 21:47 UTC, baurt commented
Good point on the cookie options.  I'll make those configurable.  I can definitely see it being a pain for development if secure was always on.  I can work on creating a way to pass the token via json.  I'd have to think how to implement that first.

2020-10-16 00:23 UTC, baurt commented on docs/api.rst
> +.. data:: tf_validation_token_set
It's mainly for testing, yes. I couldn't think of another way to save the value for verification.

2020-10-16 02:38 UTC, baurt commented on tests/test_two_factor.py
> +
I wrote a test for just changing the `fs_uniquifier` as well as using `reset_user_access()` with different config.

2020-10-16 02:39 UTC, baurt commented
> unified_signin also calls tf_login - so it needs the same new logic...
> 
> * I made a few comments about the remember token/cookie w.r.t. JSON. Should we support non-form/JSON front ends to be able to save the token (i.e. return the token on successfull login) and they can return it on next login attempt? or say that this feature relies on cookies?
>   Not sure myself which way to go.
> 
> I haven't looked carefully at the default cookie options - but this one should be http-only, probably secure, and maybe same-site?

I'll have to take a look at the unified signin.  I haven't looked much into it, so I may need a little help with tests.  I can create the logic, but the tests might evade me.

2020-10-16 19:35 UTC, baurt commented on docs/api.rst
> +.. data:: tf_validation_token_set
I removed the signal.  It doesn't really even make sense to check the value of the token in this context.  If it didn't set the correct value, the verification of the cookie would fail.

2020-10-16 20:00 UTC, baurt commented
I think I got everything.  I figured out the unified signin stuff.  That is impressive work.

2020-10-18 14:41 UTC, jwag956 commented on docs/configuration.rst
> +.. py:data:: TWO_FACTOR_VALIDITY_COOKIE_HTTPONLY
One thing I did with CSRF_COOKIE was to simply have the developer provide the appropriate dict for cookie setting - in this case we wouldn't need to allow them to change the 'key'/name - but have them supply the qwargs/dict. That way flask-security isn't in the way of providing whatever cookie settings werkzeug allows. That might make sense here rather than 3 config variables. We could make the default dict http-only, lax...

2020-10-19 14:50 UTC, baurt commented on docs/configuration.rst
> +.. py:data:: TWO_FACTOR_VALIDITY_COOKIE_HTTPONLY
Good point.  I've committed those changes.

2020-10-20 12:58 UTC, jwag956 commented on docs/configuration.rst
> +    Default: ``{'httponly': False, 'secure': False, 'samesite': None}``.
Nit: I think this should be 'True' by default - there is no reason javascript etc needs to look at this.

2020-10-20 12:59 UTC, jwag956 commented on flask_security/core.py
> +        "httponly": False,
nit: I think this should be true...

2020-10-20 13:07 UTC, jwag956 requested changes
This is looking really good - thanks for all the work.

As I noted - I think the cookie should default to httponly - since there is no reason for scripts to be able to see it.

Second - and hopefully last - please update the openapi.yml to document the new JSON return token. There are basic instructions for how to do that in CONTRIBUTING.rst.

Thanks!

2020-10-20 15:38 UTC, baurt commented
I'm not sure if I updated the openapi.yaml correctly.  Let me know if I need to change anything.

2020-10-21 01:40 UTC, jwag956 approved these changes

2020-10-21 01:41 UTC, merged

2020-10-21 01:41 UTC, jwag956 commented
Thanks for all the hard work!

2020-10-21 18:31 UTC, baurt commented
My pleasure. Thank you for maintaining this package.