ISS 983 Allow for side redirects with new configuration
Flask-Middleware/flask-security pull request #984
Opened 2024-05-30 16:58 UTC by mchineboy

Allows for a new configuration variable to control which subdomains are allowed to be redirected to. 

Resolves Flask-Middleware/flask-security#983

2024-05-30 17:50 UTC, jwag956 requested changes
So it seems like this is slightly too complex - and would need a bunch more documentation to explain that REDIRECT_MATCH_SUBDOMAINS supersedes REDIRECT_ALLOW_SUBDOMAINS.

Could we simplify this and keep it backwards compatible by defaulting REDIRECT_MATCH_SUBDOMAINS to SERVER_NAME - then we don't need the fallback code in utils.py ....

2024-05-30 17:50 UTC, jwag956 commented on flask_security/utils.py
> +            if (
Could you add a comment for this block describing the behavior?

2024-05-30 18:10 UTC, mchineboy reviewed
> Could we simplify this and keep it backwards compatible by defaulting REDIRECT_MATCH_SUBDOMAINS to SERVER_NAME - then we don't need the fallback code in utils.py ....

This was done intentionally because I feel that configuring this setting indicates that you want more explicit control over what you can redirect to. 

>Could you add a comment for this block describing the behavior?

Done!

2024-05-30 18:12 UTC, mchineboy commented on flask_security/utils.py
> +            if (
Completed.

2024-05-30 18:34 UTC, mchineboy commented
Should be the last commit for this. I was missing a return False if REDIRECT_ALLOW_SUBDOMAINS was false. Passes all tests locally.

2024-05-30 20:29 UTC, jwag956 requested changes
A few small things - but one large one - I think you (mistakenly?) implemented allowing redirects to any domain - not just subdomains.

2024-05-30 20:29 UTC, jwag956 commented on docs/configuration.rst
> +    For security reasons, if this setting is configured then the default behavior of
I think we need some additional details here. First - '... is configured then the behavior described above for SECURITY_REDIRECT_ALLOW_SUBDOMAINS is replaced by the list configured here'...

Second - The 'If you do not wish this' - if you add '.example.com' to the list then aren't you right back at the behavior above? Why would one want that... I must be missing an example?

2024-05-30 20:29 UTC, jwag956 commented on flask_security/utils.py
> +                if (len(allowed_subdomains) > 0):
doesn't this have to be true if with the stmt above?

Also - one of my favorite 3.8 added features is assignments in conditionals:

if allowed_subdomains := config_value("xxx"):

I am surprised that black allowed all the extra parens - no need for that in python!

2024-05-30 20:29 UTC, jwag956 commented on flask_security/utils.py
> +
waay tooo much white space - lets remove blank lines between comment and following if stmt.

2024-05-30 20:29 UTC, jwag956 commented on docs/configuration.rst
> +    ``['auth.example.com']`` will only allow the auth.example.com subdomain to be redirected to.
I think this isn't quite right - you are allowing application to specify the entire netloc - not just subdomain - I am not there with allowing that (and I don't think you intended that either).

So I think we can make this more secure and simpler! by saying this is an explicit list of subdomains. If you want all subdomains - leave this empty. Then the implementation in utils looks very similar to the existing - concatenating each subdomain onto base_domain.

2024-05-30 21:56 UTC, mchineboy commented on docs/configuration.rst
> +    ``['auth.example.com']`` will only allow the auth.example.com subdomain to be redirected to.
> So I think we can make this more secure and simpler! by saying this is an explicit list of subdomains. If you want all subdomains - leave this empty. Then the implementation in utils looks very similar to the existing - concatenating each subdomain onto base_domain.

Ostensibly, this works for me. I do know what I want redirected in this case. To implement that, it's simply removing the `else if` after the second check.

But there is an arguable use case that does exist where a user may want to whitelist an entire domain `.example.com`. The same configuration is allowable in CORS and I personally believe that we'd be better served following the CORS example. However, I'm not married to that idea and am happy to accept a list of strictly matched domains since it solves my own use case anyway. :)

2024-05-30 22:29 UTC, mchineboy commented
@jwag956 Reimplemented with simpler logic. Let me know if this works for you.

2024-05-30 22:40 UTC, mchineboy commented on docs/configuration.rst
> +    For security reasons, if this setting is configured then the default behavior of
Rewritten for clarity.

2024-05-30 22:40 UTC, mchineboy commented on docs/configuration.rst
> +    ``['auth.example.com']`` will only allow the auth.example.com subdomain to be redirected to.
Adjusted for new logic.

2024-05-30 22:46 UTC, mchineboy commented on docs/configuration.rst
> +    For security reasons, if this setting is configured then the default behavior of
Corrected.

2024-05-30 22:47 UTC, mchineboy commented on flask_security/utils.py
> +                if (len(allowed_subdomains) > 0):
Kinda corrected.

2024-05-30 22:47 UTC, mchineboy commented on flask_security/utils.py
> +
Removed.

2024-05-31 01:31 UTC, jwag956 requested changes

2024-05-31 01:31 UTC, jwag956 commented on flask_security/utils.py
> +            allowed_subdomains = []
This is getting close! and much simpler. However - I still think this is enabling redirects to arbitrary hosts - not just subdomains. I don't think your use case needs that and would be a bigger/more risky change. To that end REDIRECT_MATCH_SUBDOMAINS should really be a list of subdomains - as in ["auth", "app", "mktg.app"] and this check should be something like:

if any(f"{n}.{base_domain}" == url_next.netloc for n in allowed_subdomains):

Of course requiring base_domain (e.g. SERVER_NAME) to be set and should always allow url_next.netloc == base_domain right?

Does that make sense?

2024-05-31 17:09 UTC, mchineboy reviewed
In our scenario, the Flask application is served under the domain `application.example.com`. However, we need the flexibility to redirect to another subdomain, specifically `service.example.com`. The standard `SERVER_NAME` configuration in Flask restricts redirect behavior to the same subdomain. We believe that it should be permissible to redirect to any subdomain within the `example.com` root domain as it falls under the same administrative jurisdiction.

To accommodate this, we propose a modification that expands on the current redirect functionality. This update adheres to a secure redirect pattern while allowing for more flexibility. As developers or administrators of the application, we consider it necessary to have the discretion to delegate redirect targets beyond the constraints imposed by `SERVER_NAME`. This change would grant us that ability, facilitating intra-domain redirects as required by our application's logic.

The onus is on the administrator to not do something wrong in this scenario. I do see a possibility where we determine the top level domain (I.E. `example.com`) and allow redirects within that domain, but blocking the user from doing something that makes no since, such as redirecting to `google.com`.

2024-05-31 17:42 UTC, mchineboy commented on flask_security/utils.py
> +            allowed_subdomains = []
Hopefully the latest change resolves this, and my explanation further down explains the desired functionality.

2024-05-31 19:34 UTC, jwag956 commented
I am traveling so responses will be slower
I understand and agree with your use case- just need to review docs around SERVER_HOST in flask

2024-05-31 20:17 UTC, mchineboy commented
> I am traveling so responses will be slower I understand and agree with your use case- just need to review docs around SERVER_HOST in flask

No hurry, we can revisit next week.

2024-06-03 16:39 UTC, jwag956 commented
I have been reviewing Flask's SERVER_NAME - I had assumed you had that set but I now assume not. The original subdomain feature - https://github.com/Flask-Middleware/flask-security/pull/367 - revolved around that.

 It appears your use case is slightly different than that - you want to redirect to a different service, not served by the same Flask application - so SERVER_NAME doesn't really help. Given that here is my proposal - I am still trying to get things simpler. (Note - while I appreciate your trying to get the TLD - it turns out that is actually very difficult (https://stackoverflow.com/questions/15460777/how-to-get-the-domainname-nametld-from-a-url-in-python)

First - leave the current feature (REDIRECT_ALLOW_SUBDOMAINS) alone and as it is.

Then - lets add 2 new configs for this feature - REDIRECT_MATCH_SUBDOMAINS - which is a list of subdomains (auth, api2.api) - with or without the leading '.'. and REDIRECT_BASE_DOMAIN - which would be 'example.com' or 'work.uk.gov').
If REDIRECT_BASE_DOMAIN is set - then each element in  REDIRECT_MATCH_SUBDOMAINS is prepended to the REDIRECT_BASE_DOMAIN and matched against the request redirect.
So - 2 different features with different configs - should be very simple and give you the flexibility you need.

2024-06-03 18:39 UTC, mchineboy commented
> I have been reviewing Flask's SERVER_NAME - I had assumed you had that set but I now assume not. The original subdomain feature - #367 - revolved around that.
> 
> It appears your use case is slightly different than that - you want to redirect to a different service, not served by the same Flask application - so SERVER_NAME doesn't really help. Given that here is my proposal - I am still trying to get things simpler. (Note - while I appreciate your trying to get the TLD - it turns out that is actually very difficult (https://stackoverflow.com/questions/15460777/how-to-get-the-domainname-nametld-from-a-url-in-python)
> 
> First - leave the current feature (REDIRECT_ALLOW_SUBDOMAINS) alone and as it is.
> 
> Then - lets add 2 new configs for this feature - REDIRECT_MATCH_SUBDOMAINS - which is a list of subdomains (auth, api2.api) - with or without the leading '.'. and REDIRECT_BASE_DOMAIN - which would be 'example.com' or 'work.uk.gov'). If REDIRECT_BASE_DOMAIN is set - then each element in REDIRECT_MATCH_SUBDOMAINS is prepended to the REDIRECT_BASE_DOMAIN and matched against the request redirect. So - 2 different features with different configs - should be very simple and give you the flexibility you need.

Should I submit a patch to implement this logic? Or is this something that you're taking on? I'm confused by the language a little.

2024-06-03 19:05 UTC, jwag956 commented
I am asking that if my proposal sounds like it satisfies your use case - change your PR to implement it. I am also happy to do it - really simple. If you want me to do this - just close the PR and I'll put one up in the next few days. Thanks for all your work either way.

2024-06-14 01:57 UTC, jwag956 commented
Hi - lets move this forward - I know some folks LIKE to contribute to open source - that's great! Others just really want/need a feature for their (more important) app to function. I do not want to discourage you from contributing. If you are in the second group - 'just need/want the feature' I am happy to implement it as I described.  Just let me know how you want to handle this. Thanks!

2024-07-21 18:47 UTC, jwag956 commented
Should be available in #1011

2024-07-21 18:47 UTC, closed without merging